name: konnectl

on:
  push:
    # branches: [ "main" ]
    tags:
      - 'v*.*.*'
    paths:
      - src/**
      - tests/**
      - .github/**
  # pull_request:
  #   branches: [ "main" ]
  #   paths:
  #     - src/**
  #     - tests/**
  #     - Readme.md
  #     - .github/**
  #
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Create .env file
      run: |
        echo "KONNECT_PAT=${{ secrets.KONNECT_PAT }}" >> .env
        echo "KONNECT_REGION=${{ secrets.KONNECT_REGION }}" >> .env
        echo "TEST_CONTROL_PLANE_ID=${{ secrets.TEST_CONTROL_PLANE_ID }}" >> .env
        echo "TEST_GATEWAY_SERVICE_ID=${{ secrets.TEST_GATEWAY_SERVICE_ID }}" >> .env
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test -- --test-threads=1
    - name: Build release
      run: cargo build --release
    - name: Package
      run: |
          tar -czvf konnectl-${{ github.ref_name }}-${{ matrix.platform }}.tar.gz -C target/release konnectctl
    - name: Upload Release Asset
      uses: actions/upload-artifact@v2
      with:
        name: konnectctl-${{ github.ref_name }}-${{ matrix.platform }}
        path: |
          konnectl-${{ github.ref_name }}-${{ matrix.platform }}.tar.gz
          konnectl-${{ github.ref_name }}-${{ matrix.platform }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Release Assets for Ubuntu
        uses: actions/download-artifact@v2
        with:
          name: konnectctl-${{ github.ref_name }}-ubuntu-latest
          path: ./release_assets/ubuntu
      - name: Download Release Assets for macOS
        uses: actions/download-artifact@v2
        with:
          name: konnectctl-${{ github.ref_name }}-macos-latest
          path: ./release_assets/macos

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets for Ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_assets/ubuntu/konnectl-${{ github.ref_name }}-ubuntu-latest.tar.gz
          asset_name: konnectl-${{ github.ref_name }}-ubuntu-latest.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Assets for macOS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_assets/macos/konnectl-${{ github.ref_name }}-macos-latest.tar.gz
          asset_name: konnectl-${{ github.ref_name }}-macos-latest.tar.gz
          asset_content_type: application/gzip

      
